PhoneBook/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using PhoneBook.Attributes;
using System.Web.Mvc;

namespace PhoneBook.Models
{
    public class Contact
    {
       // [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
       // [Required(ErrorMessage = "Поле должно быть установлено")]
        [NonNumeric(ErrorMessage ="Не может начинаться с 1")]
        [Display(Name = "Имя")]
        public string FirstName { get; set; }

       // [Required(ErrorMessage = "Поле должно быть установлено")]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }
       // [Required(ErrorMessage = "Поле должно быть установлено")]
        [Display(Name = "Должность")]
        public string Position { get; set; }

        List<Phone> Phones = new List<Phone>();

    }
}

PhoneBook/Models/ContactContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace PhoneBook.Models
{
    public class ContactContext:DbContext
    {
        public DbSet<Contact> Contacts { get; set; }

        public DbSet<Phone> Phones { get; set; }

        public DbSet<Groups> Groups { get; set; }
    }
}

PhoneBook/Models/ContactDbInitializer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace PhoneBook.Models
{
    public class ContactDbInitializer : DropCreateDatabaseAlways<ContactContext>
    {

        protected override void Seed(ContactContext db)
        {
            db.Contacts.Add(new Contact { FirstName = "Alex", LastName = "Medved", Position = "student" });
            db.Contacts.Add(new Contact { FirstName = "John", LastName = "Smith", Position = "cook" });
            db.Contacts.Add(new Contact { FirstName = "Jack", LastName = "Williams", Position = "Senior developer" });

            db.Phones.Add(new Phone {Value = "+3809948745" });
            db.Phones.Add(new Phone {Value = "+3809948712" });
            db.Phones.Add(new Phone {Value = "+3809948712" });

            db.Groups.Add(new Groups { Name = "Колеги"});

            base.Seed(db);
        }
    }
}

PhoneBook/Models/Groups.cs
using PhoneBook.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace PhoneBook.Models
{
    public class Groups
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Name")]
        [NonNumeric(ErrorMessage = "Не может начинаться с данного символа")]
        [Reverse(ErrorMessage = "Не может заканчиваться на данный символ")]
        public string Name { get; set; }
    }
}

PhoneBook/Models/Phone.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhoneBook.Models
{
    public class Phone
    {

        public string Id { get; set; }

        public string Value { get; set; }

    }
}

PhoneBook/Controllers/ContactController.cs
using PhoneBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhoneBook.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        ContactContext db = new ContactContext();


        public ActionResult Index()
        {
            IEnumerable<Contact> contacts = db.Contacts;
            IEnumerable<Phone> phones = db.Phones;
            return View(contacts);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Add(Contact contact)
        {
            db.Contacts.Add(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            Contact contact = db.Contacts.Find(id);

            if(contact != null)
            {
                db.Contacts.Remove(contact);
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");

        }

        public ActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Update(int? Id,Contact model)
        {
           
            Contact contact = db.Contacts.Find(Id);
            db.Contacts.Remove(contact);
            db.Contacts.Add(model);
            
            db.SaveChanges();

            return RedirectToAction("Index");
           
        }
    }
}

PhoneBook/Controllers/GroupController.cs
using PhoneBook.Models;
using PhoneBook.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PhoneBook.Controllers
{
    public class GroupController : Controller
    {

        private IGroupApiService _groupApiService = new GroupApiServices();

        ContactContext db = new ContactContext();
        // GET: Group


        public async Task<ActionResult> List()
        {
            //IEnumerable<Groups> groups = db.Groups;
            var groupsList = await _groupApiService.Getlist();
           // groupsList = db.Groups;
            return View(groupsList); 
        }
        [AllowAnonymous]
        public ActionResult Additional()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Additional(Groups group)
        {
            
            if (!ModelState.IsValid)
                return View(group);

            db.Groups.Add(group);
            db.SaveChanges();
            return RedirectToAction("List");            
        }

        public ActionResult Delete(int? id)
        {
            Groups group = db.Groups.Find(id);

            if (group != null)
            {
                db.Groups.Remove(group);
                db.SaveChanges();
            }

            return RedirectToAction("List");

        }
        public ActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Update(int? Id, Groups model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            Groups group = db.Groups.Find(Id);
            db.Groups.Remove(group);
            db.Groups.Add(model);

            db.SaveChanges();

            return RedirectToAction("List");

        }

    }
}

PhoneBook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PhoneBook/Views/Contact/Add.cshtml
@model PhoneBook.Models.Contact
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm("Add", "Contact", FormMethod.Post))
{
    @Html.Partial("Partials/_DisplayTextBox")

    <input type="submit" name="Добавить" />
}

PhoneBook/Views/Contact/Index.cshtml
@model IEnumerable<PhoneBook.Models.Contact>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Телефонная книга</title>
</head>
<body>
    <div>
        <h3>Контакты</h3>
        <table>
            <tr>
                <td><p>Имя</p></td>
                <td><p>Фамилия</p></td>
                <td><p>Должность</p></td>
                <td></td>
            </tr>
            @foreach (var contact in Model)
            {
                <tr>
                    <td><p>@contact.FirstName</p></td>                    
                    <td><p>@contact.LastName</p></td>
                    <td>
                        <p>
                            @contact.Position @Html.ActionLink("Редактировать","Update", routeValues: new { id = contact.Id })
                            @Html.ActionLink("Удалить","Delete",routeValues: new { id = contact.Id })
                        </p>
                    </td>
                </tr>
            }
        </table>
    </div>
    @Html.ActionLink("Добавить", "Add", "Contact")
</body>
</html>

PhoneBook/Views/Contact/Partials/_DisplayTextBox.cshtml
@model PhoneBook.Models.Contact


@Html.LabelFor(x => x.FirstName, "Имя")
<br />
@Html.EditorFor(x => x.FirstName)
<br /><br />
@Html.LabelFor(x => x.LastName, "Фамилия")
<br />
@Html.EditorFor(x => x.LastName)
<br /><br />
@Html.LabelFor(x => x.Position, "Должность")
<br />
@Html.EditorFor(x => x.Position)
<br /><br />

PhoneBook/Views/Contact/Update.cshtml
@model PhoneBook.Models.Contact
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>


@using (Html.BeginForm("Update", "Contact", FormMethod.Post))
{
    @Html.Partial("Partials/_DisplayTextBox")

    <input type="submit" name="Добавить" />
}

PhoneBook/Views/Group/Additional.cshtml
@model PhoneBook.Models.Groups
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm("Additional", "Group", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
    @Html.Partial("Partials/_groups")

    //<input type="submit" name="Добавить" />
}

PhoneBook/Views/Group/List.cshtml
@model List<Phonebook.Models.DataModels.Group>
    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Телефонная книга</title>
    </head>
    <body>
        <div>
            <h3>Группы</h3>
            <table>
                <tr>
                    <td><p>Название</p></td>                    
                    <td></td>
                </tr>
                @foreach (var group in Model)
                {
                    <tr>                       
                        <td>
                            <p>
                                @group.Name @Html.ActionLink("Редактировать", "Update", routeValues: new { id = group.Id })
                                @Html.ActionLink("Удалить", "Delete", routeValues: new { id = group.Id })
                            </p>
                        </td>
                    </tr>
                }
            </table>
        </div>
        @Html.ActionLink("Добавить", "Additional", "Group")
    </body>
</html>

PhoneBook/Views/Group/Partials/_groups.cshtml
@model PhoneBook.Models.Groups


<div class="form-group">
    @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger  " })

    </div>

    <input type="submit" name="Отправить" />

PhoneBook/Views/Group/Update.cshtml
@model PhoneBook.Models.Groups
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>


@using (Html.BeginForm("Update", "Group", FormMethod.Post))
{
    @Html.Partial("Partials/_groups")
   
}

PhoneBook/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PhoneBook/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PhoneBook/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PhoneBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                    <li>@Html.ActionLink("Group", "List", "Group")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>